title: Rebecca Michelson # Rebecca Michelson
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > #(remove <br> elements if you don't need line breaks)
  ğŸ’¡Design-Researcher
  <br><br>
  ğŸ“Seattle, WA
  <br><br>
  ğŸŒŠ A rising tide lifts all boats
  <a href="https://www.linkedin.com/in/beckymichelson/">View My LinkedIn Profile</a>
google_analytics: UA-000000-0 #UA-147437739-1
